### ISSUE TITLE
无法解析 /swagger-ui.html

### ISSUE THREAD

**Issue by wajncn** [jiayx/swagger-ui-chrome#1]
1. 输入xxx.com/swagger-ui.html 无法解析.   我在想这里能不能自动做一个容错. 比如输入的/swagger-ui.html 就让转换成 /v2/api-docs 这样就能解析成功啦.
2. 解析成功的历史记录能不能保存下来.  这样就可以防止再次输入啦.

**Comment by jiayx** [comment]
1. 今天尝试了一下，由于用户输入地址后，是由 swagger-ui 的 js 处理，暂时没想到比较好的办法在用户输入后做出修改
2. 目前可以保存最近一次输入的地址

顺便更新了一下 Chrome 应用商店的版本，最新版 1.3 等审核通过就可以更新了

**Comment by wajncn** [comment]
多谢.   等更新后我尝试下.
在 2021年12月6日 +0800 PM5:28，jiayx ***@***.***>，写道：
