### ISSUE TITLE
无法发送https请求

### ISSUE THREAD

**Issue by Dragon-Tab** [jiayx/swagger-ui-chrome#3]
因为站点强制要求使用https协议进行访问
如果在host位置添加"https://"那结果如下
![image](https://github.com/jiayx/swagger-ui-chrome/assets/53103912/6ff120fb-b5c1-4fbe-87d3-bde803d28325)
如果不加"https://" 那么默认使用http协议发送请求
![image](https://github.com/jiayx/swagger-ui-chrome/assets/53103912/79960c48-1be0-4e7c-acac-6de81a5144d3)

**Comment by jiayx** [comment]
「host位置」是指哪里？我测试了 https 站点，也是可以正常使用的。

我猜测这里的问题可能不是扩展导致的，可以提供更多信息吗，一起排查一下

**Comment by Dragon-Tab** [comment]
这个插件不是默认发送http请求吗？你是如何发送https请求的

**Comment by jiayx** [comment]
你试试输入框里填写这个：https://petstore.swagger.io/v2/swagger.json ，他的 api 就是 https 的

**Comment by Dragon-Tab** [comment]
非常感谢 问题解决了。
在swagger.json中添加    "schemes": [ "https", "http" ]使得协议可以自己选择
